language: ruby
rvm:
  - 2.2.3
before_install:
  - rvm install 2.2.3
install:
  - bundle install --path vendor/bundle
script:
  - git config --global user.name '${GIT_NAME}'
  - git config --global user.email '${GIT_NAME}'
  - git remote set-url origin https://allgemeinmedizin-haren:${GH_TOKEN}@github.com/allgemeinmedizin-haren/allgemeinmedizin-haren.github.io.git
  - bundle exec middleman build
  - git add -A build
  - git commit --allow-empty -m "Automated Deploy"
  - git push --force origin master
branches:
  only:
  - master
